name: Deploy web app to Azure Static Web Apps


on:
  push:
   branches:
   - main
jobs:
  build_and_deploy: 
    runs-on: ubuntu-20.04
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          skip_api_build: true

  
